
# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/bicycolet/bicycolet
    steps:
      - checkout

      - run:
          name: "Setup go mod"
          command: |
            echo 'export GO111MODULE=on' >> $BASH_ENV

      - run: sudo apt update
      - run: sudo apt install curl jq shellcheck make
      - run: make setup
      - run: make check
